name: demo_project
on:
  push:
    branches:
      - main
      
jobs:
  demo_project:
    name: deploy a demo project
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
      
      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY}}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H ${{ secrets.EC2_HOST}} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            
            # Install nginx if not installed
            if ! command -v nginx >/dev/null 2>&1; then
              sudo apt update -y || sudo yum update -y
              sudo apt install -y nginx || sudo yum install -y nginx
            fi

            sudo systemctl enable nginx
            sudo systemctl start nginx

            # Clone or update website
            if [ ! -d "/var/www/html/.git" ]; then
              sudo rm -rf /var/www/html/*
              sudo git clone https://github.com/Al-Fahad/demo_app.git /var/www/html
            else
              cd /var/www/html
              sudo git pull
            fi

            sudo chown -R nginx:nginx /var/www/html
            sudo systemctl restart nginx  
          EOF